name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        node: [latest, current]
        os: [ windows-latest, ubuntu-latest, macos-latest ]

    runs-on:  ${{ matrix.os }}

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
